/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-22 03:03:00
*/

package com.silvera.User.service.base;

import com.silvera.User.domain.model.*;


public interface IUserService {

    // Auto-generated CRUD methods
    
    
    
    public User createUser(User user);
    
    
    public User updateUser(java.lang.String id, User userUpdate);
    
    
    public User readUser(java.lang.String id);
    
    
    public void deleteUser(java.lang.String id);
    
    


    
     
    
    public java.lang.Boolean userExists(java.lang.String username) ;
    

}