/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-22 03:03:00
*/

package com.silvera.Scipaper.controller;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import com.silvera.Scipaper.service.base.*;
import com.silvera.Scipaper.domain.model.*;
import com.silvera.Scipaper.messages.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.core.KafkaTemplate;
import javax.validation.Valid;


@RefreshScope
@RestController
public class ScipaperController {

    @Autowired
    IScipaperService scipaperService;

    // Auto-generated CRUD methods
    

    //
    // Public functions
    //
    
    

    @GetMapping(value="publishpaper/{id}")


    public Paper publishPaper(@PathVariable java.lang.Integer id){
        
        return scipaperService.publishPaper(id);

    }
    

    //
    // Message consumers
    //
    
}