/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-22 03:03:00
*/

package com.silvera.Scipaper.service.base;

import org.springframework.stereotype.Service;
import com.silvera.Scipaper.domain.model.*;
import com.silvera.Scipaper.messages.*;
import org.springframework.beans.factory.annotation.Autowired;


public interface IScipaperService {

    // Auto-generated CRUD methods
    

    
    public Paper publishPaper(java.lang.Integer id);
    

    

}