/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-22 12:12:03
*/

package com.silvera.Scipaper.service.base;

import com.silvera.Scipaper.domain.model.*;

import java.util.Optional;


public interface IScipaperService {

    // Auto-generated CRUD methods
    
    
    
    public Paper createPaper(Paper paper);
    
    
    public Paper updatePaper(java.lang.Integer id, Paper paperUpdate);
    
    
    public Optional<Paper> readPaper(Integer id);
    
    
    public void deletePaper(java.lang.Integer id);


    public java.util.List<Paper> papers();
    
    public Paper publishPaper(java.lang.Integer id, String username);
    

    

}