/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-22 03:03:00
*/

package com.silvera.Scipaper.repository;

import com.silvera.Scipaper.domain.model.Paper;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface PaperRepository extends MongoRepository<Paper, java.lang.Integer> {
  // CRUD operations are included in MongoRepository interface

}