/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-22 12:12:03
*/

package com.silvera.Scipaper.repository;

import com.silvera.Scipaper.domain.model.Section;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface SectionRepository extends MongoRepository<Section, java.lang.String> {
  // CRUD operations are included in MongoRepository interface

}